name: h4c
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - pandas
  - scipy
  - numpy
  - libblas[build=*mkl]
  - h5py
  - astropy
  - pyuvdata
  - healpy
  - astropy-healpix
  - pympler
  - pip:
    - pyuvsim
    - pyradiosky
    - git+https://github.com/hera-team/vis_cpu@progress
    - git+https://github.com/hera-team/hera_sim@memory-profiling
    - git+https://github.com/telegraphic/pygdsm
    - line_profiler

